version: "3"
services:
  db:
    image: "mongo:3-stretch"
    volumes:
      - ~/mongodb:/data/db
    ports:
      - 27017:27017
  app:
    cap_add:
      - NET_ADMIN
    build: .
    environment:
      TOKEN: ${TOKEN}
    ports:
      - 4000:3001
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:27017", "--", "yarn", "gulp"]