version: '2'
services:
  # redis:
  #   image: "redis:alpine"
  #   ports:
  #     - "6379:6379"
  # db:
  #   image: "mysql:5.7.13"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 1qazXSW@
  #     MYSQL_DATABASE: courcasa_membership
  #   volumes:
  #     - ~/db:/var/lib/mysql
  #     - ./docker_configs/my.cnf:/etc/mysql/my.cnf
  #   ports:
  #     - "3306:3306"
  mariadb:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
      # MYSQL_USER: mybb
      # MYSQL_PASSWORD: changeme
  app:
    stdin_open: true
    tty: true
    build: .
    command: npm run dev
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      PORT: 4000
      NODE_ENV: development
    depends_on:
      - mariadb
      # - redis
    logging:
      driver: json-file