version: '2'
services:
  # redis:
  #   image: "redis:alpine"
  #   ports:
  #     - "6379:6379"
  db:
    image: "mongo:3-stretch"
    volumes:
      - ${DB_PATH}:/data/db
    ports:
      - 27017:27017
  app:
    stdin_open: true
    tty: true
    build: .
    command: npm run dev
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      PORT: 4000
      NODE_ENV: development
    # depends_on:
    #   - db
      # - redis
    logging:
      driver: json-file